export const NEAR_RPC_ENDPOINTS = [
  'https://rpc.mainnet.near.org',
  'https://rpc.mainnet.pagoda.co',
  'https://1rpc.io/near',
  'https://rpc.ankr.com/near',
  'https://near.drpc.org',
  'https://rpc.web4.near.page',
  'https://free.rpc.fastnear.com',
  'https://getblock.io/nodes/near/',
  'https://near.lava.build',
  'https://near.lavenderfive.com/',
  'https://nodereal.io/api-marketplace/near-rpc',
  'https://endpoints.omniatech.io/v1/near/mainnet/public',
  'https://api.seracle.com/saas/baas/rpc/near/mainnet/public/',
  'https://near-mainnet.gateway.tatum.io',
]
